### ISSUE TITLE
Namespacing wrong for GuzzleHttp

### ISSUE THREAD

**Issue by johnknl** [Stormsys/SimpleHal#1]
In `GuzzleHalClient`, `Guzzle\Http\ClientInterface` is referenced. The root namespace for Guzzle is `GuzzleHttp`. Not sure when this happened, quick fix might be adjusting composer.json to reference an earlier version. Better would be to adjust the namespacing in SimpleHal.

**Comment by Stormsys** [comment]
It seems like the lock file was pointing to an older version of the API, it has now been updated to the latest namespaces and API - Thanks!
